##
## Test Suites
##

    modified.files.includes[relevant][headless-builder-java-rule]=\
        **/*.java,\
        **/test/**,\
        **/testIntegration/**,\
        modules/apps/object/object-admin-rest-api/**/*.java,\
        modules/apps/object/object-admin-rest-client/**/*.java,\
        modules/apps/object/object-admin-rest-client-js/**/*.java,\
        modules/apps/object/object-admin-rest-impl/**/*.java,\
        modules/apps/object/object-api/**/*.java,\
        modules/apps/object/object-dynamic-data-mapping/**/*.java,\
        modules/apps/object/object-dynamic-data-mapping-form-field-type/**/*.java,\
        modules/apps/object/object-dynamic-data-mapping-form-field-type-api/**/*.java,\
        modules/apps/object/object-info-api/**/*.java,\
        modules/apps/object/object-js-components-web/**/*.java,\
        modules/apps/object/object-rest-api/**/*.java,\
        modules/apps/object/object-rest-impl/**/*.java,\
        modules/apps/object/object-rest-test-util/**/*.java,\
        modules/apps/object/object-scripting-api/**/*.java,\
        modules/apps/object/object-scripting-impl/**/*.java,\
        modules/apps/object/object-service/**/*.java,\
        modules/apps/object/object-web/**/*.java

    modified.files.includes[relevant][headless-builder-playwright-rule]=**

    relevant.rule.names=\
        headless-builder-java-rule,\
        headless-builder-playwright-rule

    test.batch.names[relevant][headless-builder-java-rule]=\
        modules-integration-mysql57,\
        modules-unit

    test.batch.names[relevant][headless-builder-playwright-rule]=\
        playwright-js-tomcat90-mysql57

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[headless-builder-java-rule][relevant][modules-integration-mysql57]=\
        **/testIntegration/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[headless-builder-java-rule][relevant][modules-unit]=\
        **/test/**/*Test.java

    playwright.projects.includes[playwright-js-tomcat90-mysql57][relevant][headless-builder-playwright-rule]=\
        headless-builder-impl,\
        headless-builder-web

##
## Testray
##

    testray.main.component.name=Headless API Builder